<template>
   <div class="q-pa-md boxes flex" >
    <h2 class="text-center full-width q-mb-xl">Features</h2>
    <div class="q-gutter-x-xl q-gutter-y-xl flex items-center justify-center text-center" >
      <div class="q-pa-md boxing flex column items-center" v-for="(item, index) in mainItems" :key="index" :class="item.class">
        <div class="holder">
          <h3>{{ item.head }}</h3>
          <img class="boxico" :src="item.boximg" />
          <div class="desc q-py-md">{{ item.desc }}</div>
          <q-btn class="btn" flat size="lg" color="white" :label="item.link" :to="item.urlx"  />
        </div >
      </div >
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      mainItems: [
        {
          class: 'item01',
          head: 'Non-Custodial',
          desc: 'No need sign-up, deposit and KYC',
          link: 'More details soon!',
          urlx: '',
          boximg: 'boxes/id.png',
        },
        {
          class: 'item02',
          head: 'Fully decentralized',
          desc: 'Scratch\'\em is a completely decentralized scratch-off game platform.',
          link: 'More details soon!',
          urlx: '',
          boximg: 'boxes/chess.png',
        },
        {
          class: 'item03',
          head: 'Provably Fair',
          desc: 'Tickets are generated by SupraOracles VRF to determine random results.',
          link: 'More details soon!',
          urlx: '',
          boximg: 'boxes/oracle.svg',
        },
        {
          class: 'item04',
          head: 'Fully transparent',
          desc: 'Scratch\'\em presents this information to you instantly.',
          link: 'More details soon!',
          urlx: '',
          boximg: 'boxes/glasses.png',
        },
        {
          class: 'item05',
          head: 'Instant payment',
          desc: 'When your ticket is rewarded, you can instantly transfer your winnings to your wallet.',
          link: 'More details soon!',
          urlx: '',
          boximg: 'boxes/money.png',
        },
        {
          class: 'item06',
          head: 'Scratch Mining',
          desc: 'Play a lot, win a lot!',
          link: 'More details soon!',
          urlx: '',
          boximg: 'boxes/award.png',
        },
      ],
      contentClass: '',
    };
  },
};
</script>

<style>

/* h2 {width: 100%;} */

.boxes {min-width: 55vw; width: 1400px; max-width: 90vw; position: relative; margin: 100px 0; flex-wrap: wrap; }

.boxes .boxing{width:28%;background:#0f141b;border-radius:20px;display:flex;flex-direction:column;  transition: all .5s ease; flex: 1 0 auto;}

.boxes .boxing .holder { flex: 1 0 auto;   perspective:1000px;perspective-origin:50% 50%; transition: all .5s ease; }
.boxes .boxing .holder * {transition: all .5s ease; }
.boxes .boxing .holder h3 {font-size: 2rem; transform: translateZ(5px); z-index: 9;}
.boxes .boxing .holder:hover h3 {transform: translateZ(70px);}

.boxes .boxing .holder .boxico {position: absolute; transform: translateZ(5px); width: 150px; z-index: 0;}
.boxes .boxing .holder:hover .boxico {transform: translateZ(90px);}

.boxes .boxing .holder .desc { transform: translateZ(5px);}
.boxes .boxing .holder:hover .desc {transform: translateZ(110px);}

.boxes .boxing .holder .btn { transform: translateZ(5px); border-radius: 20px;}
.boxes .boxing .holder:hover .btn {transform: translateZ(130px);}

.item01 .boxico {top: -99px; right: -90px; }
.item02 .boxico {bottom: -60px; left: -40px; }
.item03 .boxico {top: -60px; left: -50px; }
.item04 .boxico {top: -50px; left: -60px; }
.item05 .boxico {bottom: -50px; right: -60px; }
.item06 .boxico {top: -50px; right: -130px; }
</style>
